cookie:
  expiry_days: 1
credentials:
  usernames:
    ayaka:
      password: $2b$12$UL7MjMefy2K86BjXI4/0v.4A78Y/QI1m3Zva6U7an6UUqDmmZZf3e
    kohei:
      password: $2b$12$LfmOSHAPZVCUaOsPIeXxyuwUA.q0UlRLPRa8gv7wTuJKmMYMp61IO
