cookie:
  expiry_days: 1
credentials:
  usernames:
    ayaka:
      password: $2b$12$sQ9j/fWMXc9xNl4ffz2dkuyeeRsk6SJUP2rusYwIrz.yOzmvq/GEi
    kohei:
      password: $2b$12$TAh9noko8yxqUXcZQdOERuPAkdpaAq1vWuJgqI8imhXYAxMVK9WYS
